# Standards: 0.11
---

# 4.1.12 Ensure use of privileged commands is collected (Scored)

- name: 4.1.12 Ensure use of privileged commands is collected (Scored)
  shell: "grep 4.1.12 {{ cis_audit_rules_filename }}"
  register: 4_1_12_line
  ignore_errors: true
  tags:
    - "4.1.12"
    - level-2
    - section-4
    - scored

- name: 4.1.12 Ensure use of privileged commands is collected (Scored)
  script: "{{ role_path }}/files/audit_4_1_12.sh"
  register: privileged_commands
  ignore_errors: true
  tags:
    - "4.1.12"
    - level-2
    - section-4
    - scored

- name: 4.1.12 Ensure use of privileged commands is collected (Scored)(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.12 Ensure use of privileged commands is collected (Scored)'
    - '{{ privileged_commands.stdout_lines }}'
  when:
    ("'# 4.1.12 Ensure use of privileged commands is collected (Scored)' not in 4_1_12.stdout")
  tags:
    - "4.1.12"
    - level-1
    - section-4
    - scored
