# Standards: 0.11
---

# 1.1.2~5 Ensure separate partition exists for /tmp (Scored)
# 1.1.3 Ensure nodev option set on /tmp partition (Scored)
# 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
# 1.1.5 Ensure noexec option set on /tmp partition (Scored)

- name: Current mounting /tmp state
  shell: "mount | grep /tmp"
  register: mount_tmp
  tags:
    - level-1
    - section-1
    - "1.1.2"
    - "1.1.3"
    - "1.1.4"
    - "1.1.5"
    - scored

- name: 1.1.2~5 - Ensure separate partition exists for /tmp and nodev,nosuid,noexec options set on /tmp (Scored)
  mount:
    name: "{{ item.mountpoint }}"
    state: present
    fstype: "{{item.fstype}}"
    src: "{{item.device}}"
    opts: "{{item.opts}}"
  with_items:
    - { mountpoint: '/tmp', device: 'tmpfs', fstype: 'tmpfs', opts: 'rw,nosuid,nodev,noexec,relatime' }
  when: "'tmpfs on /var/tmp type tmpfs (rw,nosuid,nodev,noexec,relatime)' not in mount_tmp.stdout"
  tags:
      - level-1
      - section-1
      - "1.1.2"
      - "1.1.3"
      - "1.1.4"
      - "1.1.5"
      - scored
